ALTER TABLE trades ADD COLUMN IF NOT EXISTS stop_loss DOUBLE PRECISION;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS take_profit DOUBLE PRECISION;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS exit_type VARCHAR(20);
